version: '3'

services:

  mysql:
    container_name: MYSQL
    image: mysql:5.7
    hostname: MYSQL
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      HOSTNAME: MYSQL
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 1s
      retries: 10

  apache:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./httpd/httpd.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      mysql:
        condition: service_healthy
      
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - apache

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
    - 85:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootroot
    links:
      - apache

volumes:
  db_data: